# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "ytr-zhang"
repo_name: "robotics-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    # --------- My Keywords ---------
    "Manipulation":
        filters: ["Robot Manipulation", "Robotic Manipulation", "Robot Learning", "Imitation Learning"]
    "VLM":
        filters: ["Vision Language Model", "Vision Language Models", "Vision-Language Model", "Vision-Language Models"]
    "VLA":
        filters: ["Vision Language Action","Vision-Language-Action"]
    "Humanoid":
        filters: ["Humanoid Robot", "Humanoid"]
    "Dexterous":
        filters: ["Dexterous Manipulation", "Dexterous hand", "Dexterity", "Dexterous"]
